### ISSUE TITLE
Subdomain matching

### ISSUE THREAD

**Issue by eldesh** [Idein/gatekeeper#25]
Domain matching rule using regex seems to overkill.
Using regex, it is hard to predict what domain matches the rule.
More restricted pattern matching syntax is preferable like:

```
address:
  Specif:
    Domain:
      # match "mail.google.com", "images.google.com", ...
      # not match "google.com", "www.images.google.com"
      pattern: "*.google.com"
```

- ref https://tools.ietf.org/html/rfc2818#section-3.1
- ref https://en.wikipedia.org/wiki/Wildcard_certificate
